development:
  adapter: async
#  adapter: redis
#  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:74de9c48e7d091fcff64ebbb4a856002@cod.redistogo.com:9645/
